### ISSUE TITLE
Where condition of includes with pagination

### ISSUE THREAD

**Issue by jValdron** [sequelize/sequelize#1432]
I have a findAndCountAll call on a Vehicle model which includes a few things (think of Make and Model for example). 

It looks something like this:

```javascript
Vehicle.findAndCountAll({
  include: [ Make, Model, Status ], // There's a lot more to it than these three, and on Status, I have specific attributes I want.
  limit: 25, // Dynamic from query string.
  offset: 0, // Same, dynamic from query string.
  where: sequelize.or(
    // I have to include a search that also searches make and model, so I have something like this:
    [ '`year` LIKE ?', '%my keywords%'],
    [ '`make`.`name` LIKE ?', '%my keywords%'],
    [ '`model`.`name` LIKE ?', '%my keywords%']
  ),
  attributes: [ ... ]
});
```

This used to work, however, the queries gets created differently now, I now have something like this:

```sql
SELECT 
    `vehicles`.*, 
    `make`.`id` AS `make.id`, `make`.`name` AS `make.name`, 
    `model`.`id` AS `model.id`, `model`.`name` AS `model.name` 
    ...
FROM (
    SELECT 
        `vehicles`.id, `vehicles`.year, // ... all the attributes I want from Vehicle
        `Status`.`id` AS `Status.id`, // ... all the attributes I want from Status
    FROM `vehicles` 
    INNER JOIN `vehicle_status` AS `Status` ON `vehicles`.`id` = `Status`.`vehicle_id` 
    WHERE (`year` LIKE '%dodge%' OR `color_name` LIKE '%dodge%' OR `make`.`name` LIKE '%dodge%' OR `model`.`name` LIKE '%dodge%')
) AS `vehicles`
LEFT OUTER JOIN `makes` AS `make` ON `make`.`id` = `vehicles`.`make_id` 
LEFT OUTER JOIN `models` AS `model` ON `model`.`id` = `vehicles`.`model_id` 
ORDER BY created_at ASC;
```

Now it generates a sub query for the FROM. I get why it does that, and it actually fixes a bug I was having with nested includes.

However, this condition no longer works. Is there any workaround or anything I'm not catching?

**Comment by laghi** [comment]
Hello,
Is this already fixed?

**Comment by mickhansen** [comment]
@laghi Not sure.

**Comment by jValdron** [comment]
Been a while, but yes, that was fixed back then.

**Comment by Djalmar** [comment]
@jValdron can you show a sample code of how finally you managed this ?

**Comment by jValdron** [comment]
Sorry @Djalmar, I haven't used Sequelize or done anything with Node in a while, and I don't have access to the code where I used this.

**Comment by sksankarraj** [comment]
Still facing this issue with nested joins on `"sequelize": "^5.21.3"`
