### ISSUE TITLE
Synchronize models to Postgresql non public schema causes error 'relation xxx does not exist'. Schema of model is ignored when creating references

### ISSUE THREAD

**Issue by TechMaster** [sequelize/sequelize#7085]
# Sequelize bug report
 
## Description
 Synchronize from sequelize models to Postgresql non public schema causes error 'relation xxx does not exist'. Sequelize ignores schema property of model when creating references between models.

Clone demo source code here https://github.com/TechMaster/bugsequelize.git
 
## Steps to reproduce
```bash
git clone https://github.com/TechMaster/bugsequelize.git
cd bugsequelize
#edit ./config/config.json to properly connect to your Postgresql database
npm install
npm start
```

```npm start``` will run syncdb.js file. The syncdb.js has commmand ```sequelize.sync()```

In models folder, there are two models: Project and Task. Project hasMany Task. Task belongsTo Project.

In ./config/config.json, I defined non public schema in schema property. 
```json
{
  "development": {
    "username": "postgres",
    "password": "abc",
    "database": "payroll",
    "host"    : "payroll",
    "dialect" : "postgres",
    "schema"  : "cms"   // Non public schema
  }
}
```

When running syncdb.js, sequelize raise error 'relation "project" does not exist'

Here is generated SQL command
```sql
CREATE TABLE IF NOT EXISTS "cms"."task" ("id"  BIGSERIAL , "title" TEXT, "project_id" BIGINT REFERENCES "project" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
```

Wrong references. This only works when scheme is 'public' 
```sql
REFERENCES "project" ("id")
```
it should be 
```sql
REFERENCES "cms"."project" ("id")
```

**Comment by TechMaster** [comment]
I believe this issue [#6336](https://github.com/sequelize/sequelize/issues/6336) has same root cause with mine

**Comment by TechMaster** [comment]
I have fixed bug and pushed to https://github.com/TechMaster/bugsequelize

**Comment by ezamelczyk** [comment]
why is it not pulled yet?

**Comment by stonedraider** [comment]
is this not working anymore? I tried to set "schema"  : "xyz" in config.json, added the code for custom_schema in index.js and have schemas specified in files with sequelize.define and migration files with "up" method. however I still get "ERROR: relation "Todos" does not exist" for TodoItems which have a reference on Todos in not public schema.

**Comment by jpwiddy** [comment]
This is still an issue. Can we get support for a configuration option?

**Comment by egorzot** [comment]
Still get the same error with sequelize 5.1.0.

**Comment by megha1697** [comment]
Still getting this error. Is the issue really fixed to set non public schema?

**Comment by SerhiiBulakh** [comment]
Have the same issue
use  
"sequelize": "^6.33.0",
"sequelize-typescript": "^2.1.5",
