### ISSUE TITLE
findOne returns null, while findAll returns single desired record

### ISSUE THREAD

**Issue by ryanmcclure4** [sequelize/sequelize#7665]
## What you are doing?
I have models `Thread`, `ChannelIntegration`, and `PhoneNumber`. These are related as such:

```
Thread.belongsTo(ChannelIntegration)
ChannelIntegration.hasMany(Thread)

PhoneNumber.belongsTo(ChannelIntegration)
ChannelIntegration.hasOne(PhoneNumber)
```
I am trying to perform a `findOne` query on `PhoneNumber`, including the `Thread` and `ChannelIntegration` models.

## What do you expect to happen?
This query should return the single PhoneNumber record I am looking for:
```
PhoneNumber.findOne({
  attributes: ['number_value', 'number_type', 'channel_integration_id'],
  include: [{
    model: ChannelIntegration,
    include: [{
      model: Thread,
      where: {
        id: message.thread_id,
      },
    }],
  }],
});
```

## What is actually happening?
The `findOne` query returns null. **If I change this to `findAll` it returns an array with a single record.** If I add `limit: 1` to the `findAll` query, it returns null (as it generates the same query as `findOne`).

SQL for `findOne`:
```
SELECT "phone_number".*, "channel_integration.threads"."id" AS "channel_integration.threads.id", "channel_integration.threads"."organization_id" AS "channel_integration.threads.organization_id", "channel_integration.threads"."type" AS "channel_integration.threads.type", "channel_integration.threads"."fake" AS "channel_integration.threads.fake", "channel_integration.threads"."status" AS "channel_integration.threads.status", "channel_integration.threads"."name" AS "channel_integration.threads.name", "channel_integration.threads"."priority" AS "channel_integration.threads.priority", "channel_integration.threads"."lifecycle" AS "channel_integration.threads.lifecycle", "channel_integration.threads"."integration_data" AS "channel_integration.threads.integration_data", "channel_integration.threads"."last_updater_id" AS "channel_integration.threads.last_updater_id", "channel_integration.threads"."parent_id" AS "channel_integration.threads.parent_id", "channel_integration.threads"."channel_integration_id" AS "channel_integration.threads.channel_integration_id", "channel_integration.threads"."channel_instance_id" AS "channel_integration.threads.channel_instance_id", "channel_integration.threads"."created_at" AS "channel_integration.threads.created_at", "channel_integration.threads"."updated_at" AS "channel_integration.threads.updated_at" FROM (SELECT "phone_number"."id", "phone_number"."number_value", "phone_number"."number_type", "phone_number"."channel_integration_id", "channel_integration"."id" AS "channel_integration.id", "channel_integration"."type_id" AS "channel_integration.type_id", "channel_integration"."organization_id" AS "channel_integration.organization_id", "channel_integration"."creator_id" AS "channel_integration.creator_id", "channel_integration"."fake" AS "channel_integration.fake", "channel_integration"."status" AS "channel_integration.status", "channel_integration"."settings" AS "channel_integration.settings", "channel_integration"."shared" AS "channel_integration.shared", "channel_integration"."integration_value" AS "channel_integration.integration_value", "channel_integration"."created_at" AS "channel_integration.created_at", "channel_integration"."updated_at" AS "channel_integration.updated_at", "channel_integration"."channel_instance_id" AS "channel_integration.channel_instance_id" FROM "phone_numbers" AS "phone_number" LEFT OUTER JOIN "channel_integrations" AS "channel_integration" ON "phone_number"."channel_integration_id" = "channel_integration"."id" LIMIT 1) AS "phone_number" INNER JOIN "threads" AS "channel_integration.threads" ON "channel_integration.id" = "channel_integration.threads"."channel_integration_id" AND "channel_integration.threads"."id" = 759;
```

SQL for `findAll`:
```
SELECT "phone_number"."id", "phone_number"."number_value", "phone_number"."number_type", "phone_number"."channel_integration_id", "channel_integration"."id" AS "channel_integration.id", "channel_integration"."type_id" AS "channel_integration.type_id", "channel_integration"."organization_id" AS "channel_integration.organization_id", "channel_integration"."creator_id" AS "channel_integration.creator_id", "channel_integration"."fake" AS "channel_integration.fake", "channel_integration"."status" AS "channel_integration.status", "channel_integration"."settings" AS "channel_integration.settings", "channel_integration"."shared" AS "channel_integration.shared", "channel_integration"."integration_value" AS "channel_integration.integration_value", "channel_integration"."created_at" AS "channel_integration.created_at", "channel_integration"."updated_at" AS "channel_integration.updated_at", "channel_integration"."channel_instance_id" AS "channel_integration.channel_instance_id", "channel_integration.threads"."id" AS "channel_integration.threads.id", "channel_integration.threads"."organization_id" AS "channel_integration.threads.organization_id", "channel_integration.threads"."type" AS "channel_integration.threads.type", "channel_integration.threads"."fake" AS "channel_integration.threads.fake", "channel_integration.threads"."status" AS "channel_integration.threads.status", "channel_integration.threads"."name" AS "channel_integration.threads.name", "channel_integration.threads"."priority" AS "channel_integration.threads.priority", "channel_integration.threads"."lifecycle" AS "channel_integration.threads.lifecycle", "channel_integration.threads"."integration_data" AS "channel_integration.threads.integration_data", "channel_integration.threads"."last_updater_id" AS "channel_integration.threads.last_updater_id", "channel_integration.threads"."parent_id" AS "channel_integration.threads.parent_id", "channel_integration.threads"."channel_integration_id" AS "channel_integration.threads.channel_integration_id", "channel_integration.threads"."channel_instance_id" AS "channel_integration.threads.channel_instance_id", "channel_integration.threads"."created_at" AS "channel_integration.threads.created_at", "channel_integration.threads"."updated_at" AS "channel_integration.threads.updated_at" FROM "phone_numbers" AS "phone_number" LEFT OUTER JOIN "channel_integrations" AS "channel_integration" ON "phone_number"."channel_integration_id" = "channel_integration"."id" INNER JOIN "threads" AS "channel_integration.threads" ON "channel_integration"."id" = "channel_integration.threads"."channel_integration_id" AND "channel_integration.threads"."id" = 759;
```

**Comment by samuel-gaunt** [comment]
I have the exact same issue and have just resorted to using findAll and returning the 1st element in that array.

**Comment by edgarmarkosov** [comment]
Is this issue fixed? As I have same issue on my side.

**Comment by grantcarthew** [comment]
Same here with this code:

```js
const dbEmail = await db.User.findAll({
        include: [{
          model: db.Email,
          where: {email: email}
        }]
      })
```

Note the User to Email relationship is many-to-many.

**Comment by srkimir** [comment]
👍

**Comment by xaiyeon** [comment]
I'm also having this issue as of late when constructing a query with findOne...

**Comment by roberttrankle** [comment]
Similar issue, using spring and hibernate...any solutions?

**Comment by frlinw** [comment]
If it's because of `limit 1` this issue has been fixed since v5-beta2 https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md#500-beta2 
https://github.com/sequelize/sequelize/pull/9248

**Comment by 09wattry** [comment]
> I have the exact same issue and have just resorted to using findAll and returning the 1st element in that array.

I tend to use ```if result.length > 0 return result[result.length - 1]``` I feel it's cleaner then ```if result[0] return result[0];```

**Comment by papb** [comment]
Fixed by #9248

**Comment by jpwiddy** [comment]
I actually still am finding this to be a bug.

Running 
```
        "sequelize": "5.21.5",
```

**Comment by MJB-Khorasani** [comment]
I have a similar problem: 
this is what I do:
```
let role = await RoleModel.findOne({
  where: { accessLevel: 4 }
});
console.log(role);
let roles = await RoleModel.findAll({
  where: { accessLevel: 4 },
  limit: 1
});
```

but in my case `limit: 1` does not have any effect. I mean, it returns the correct record. in my case when I use findAll. but findOne cannot fetch the record

**Comment by pdxJaxon** [comment]
As of today, this is still an issue as far as I can tell.

I am working around it via  .findAll({limit:1})

**Comment by elnur0000** [comment]
this is still an issue

**Comment by Iuriiiii** [comment]
Our class find out this bug in plain class 😂

**Comment by mark-p-r-robinson** [comment]
Still having this issue. As others suggested I am now using findAll with limit:1, but it seems like findOne should be fixed. 
adding subQuery:false to findOne didn't work for me.
